# Generated by Django 2.2.6 on 2020-01-29 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20200129_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='due_date',
            field=models.DateTimeField(),
        ),
    ]
